---
image:
  distribution: ubuntu
  release: impish
  architecture: amd64
  name: "{{ image.distribution }}-{{ image.release }}-{{ image.variant }}-{{ image.serial }}"
  description: "Ubuntu {{ image.release }} ({{ image.variant }}-{{ image.serial }})"
  variant: default

source:
  downloader: debootstrap
  url: http://archive.ubuntu.com/ubuntu
  variant: minbase

mappings:
  architecture_map: debian

targets:
  lxd:
    vm:
      filesystem: ext4
      size: 21474836480 # 20 GiB

packages:
  manager: apt
  cleanup: true
  update: true
  repositories:
  - name: sources.list
    url: |-
      deb http://archive.ubuntu.com/ubuntu {{ image.release }} main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu {{ image.release }}-updates main restricted universe multiverse
      deb http://security.ubuntu.com/ubuntu {{ image.release }}-security main restricted universe multiverse
  sets:
  - packages:
    - bash-completion
    - cloud-init
    - curl
    - diffutils
    - fuse
    - iputils-ping
    - jq
    - less
    - language-pack-en
    - lsof
    - man-db
    - manpages
    - netcat-openbsd
    - netplan.io
    - openssh-server
    - openssh-client
    - rsync
    - sudo
    - socat
    - strace
    - systemd
    - tcpdump
    - tmux
    - tree
    - udev
    - unzip
    - vim
    - wget
    action: install

  - packages:
    - apparmor
    - apparmor-profiles
    - cloud-guest-utils
    - grub-efi-amd64-signed
    - linux-virtual
    - shim-signed
    - lvm2
    action: install
    types:
    - vm
  
  - packages:
    - unattended-upgrades
    - networkd-dispatcher
    - os-prober
    - packagekit
    action: remove

actions:
  # Generate machine-id in order for the kernel stuff to be configured properly
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemd-machine-id-setup
    types:
    - vm

  # Manage systemd-resolved stub
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      umount -l /etc/resolv.conf || true
      rm /etc/resolv.conf
      ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

  # Configure timezone
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      ln -sfn /usr/share/zoneinfo/Europe/Paris /etc/localtime
      echo "Europe/Paris" > /etc/timezone

  # Default systemd units to enable
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemctl enable systemd-networkd systemd-resolved ssh cloud-init

  # Additionnal units to manage for VMs
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemctl enable systemd-timesyncd
    types:
      - vm

  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      # Make sure the locale is built and functional
      locale-gen en_US.UTF-8
      update-locale LANG=en_US.UTF-8
      # Cleanup underlying /run
      mount -o bind / /mnt
      rm -rf /mnt/run/*
      umount /mnt
      # Cleanup temporary shadow paths
      rm /etc/*-

  - trigger: post-files
    action: |-
      #!/bin/sh
      set -eux
      TARGET="x86_64"
      update-grub
      grub-install --uefi-secure-boot --target="${TARGET}-efi" --no-nvram --removable
      update-grub  
      sed -i "s#root=[^ ]*#root=/dev/sda2#g" /boot/grub/grub.cfg
      # Re-generate initramfs
      update-initramfs -u -k all
    types:
    - vm

files:
  - name: fstab
    generator: fstab
    types:
    - vm

  - path: /etc/fstab
    generator: dump
    types:
    - container

  - path: /etc/machine-id
    generator: dump
  
  - path: /var/lib/dbus/machine-id
    generator: remove
  
  - path: /etc/hostname
    generator: hostname
  
  - path: /etc/hosts
    generator: hosts

  - name: lxd-agent
    generator: lxd-agent
    types:
    - vm

  - path: /etc/resolvconf/resolv.conf.d/original
    generator: remove

  - path: /etc/resolvconf/resolv.conf.d/tail
    generator: remove

  - name: meta-data
    generator: cloud-init

  - name: network-config
    generator: cloud-init

  - name: user-data
    generator: cloud-init

  - path: /etc/default/grub.d/50-lxd.cfg
    generator: dump
    content: |-
      GRUB_RECORDFAIL_TIMEOUT=0
      GRUB_TIMEOUT=0
      GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} console=tty1 console=ttyS0"
      GRUB_TERMINAL=console
    types:
    - vm

  # Fix behavior where initramfs will search for an non-existing swap partition on boot (the kernel will take more than 30sec to boot...)
  # Caused by building images on a machine with swap (i.e LXD host)
  - path: /etc/initramfs-tools/conf.d/resume
    generator: dump
    content: |-
      RESUME=none
    types:
    - vm

  - path: /etc/sysctl.d/90-tuning.conf
    generator: dump
    content: |-
      vm.dirty_ratio = 30
      vm.dirty_background_ratio = 10
    types:
    - vm

  - path: /etc/udev/rules.d/90-tuning.conf
    generator: dump
    content: |-
      ACTION=="add|change", KERNEL=="sd[a-z]", SUBSYSTEM=="block", ATTR{queue/scheduler}="none"
      ACTION=="add|change", KERNEL=="sd[a-z]", SUBSYSTEM=="block", ATTR{queue/read_ahead_kb}="4096"
    types:
    - vm

  - path: /etc/netplan/90-config.yaml
    generator: dump
    content: |-
      network:
        version: 2
        ethernets:
          eth0:
            dhcp4: true
            dhcp-identifier: mac
    types:
    - container

  - path: /etc/netplan/90-config.yaml
    generator: dump
    content: |-
      network:
        version: 2
        ethernets:
          enp5s0:
            dhcp4: true
            dhcp-identifier: mac
    types:
    - vm

  - path: /etc/systemd/resolved.conf
    generator: dump
    content: |-
      Cache=yes
      DNSStubListener=yes
      ReadEtcHosts=yes

  - path: /etc/systemd/journald.conf
    generator: dump
    content: |-
      [Journal]
      Storage=persistent
      Compress=yes
      SystemMaxUse=1G
      SystemMaxFileSize=100M
      MaxRetentionSec=7day

  - path: /etc/systemd/timesyncd.conf
    generator: dump
    content: |-
      [Time]
      NTP=0.fr.pool.ntp.org pool 1.fr.pool.ntp.org pool 2.fr.pool.ntp.org
    types:
    - vm

  # Disable automatic service start after deb package install
  - path: /usr/sbin/policy-rc.d
    generator: dump
    mode: 755
    content: |-
      #!/bin/sh
      exit 101

  - path: /etc/ssh/sshd_config
    generator: dump
    content: |-
      Port 22
      HostKey /etc/ssh/ssh_host_ed25519_key
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 30s
      PermitRootLogin no
      AuthenticationMethods publickey
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
      AuthorizedKeysFile .ssh/authorized_keys
      UsePAM yes
      X11Forwarding no
      AllowAgentForwarding yes
      PrintMotd yes
      Subsystem sftp internal-sftp

  - path: /etc/cloud/cloud.cfg
    generator: dump
    content: |-
      #cloud-config
      users:
        - default
      ssh:
        emit_keys_to_console: false
      cloud_init_modules:
        - write-files
        - users-groups
        - ssh
      cloud_config_modules: {}
      cloud_final_modules: {}
      system_info:
        distro: ubuntu
        default_user:
          name: core
          lock_passwd: false
          groups: [sudo, adm, systemd-journal]
          sudo: ["ALL=(ALL) NOPASSWD:ALL"]
          shell: /bin/bash
        ssh_svcname: ssh

  - path: /etc/tmux.conf
    generator: dump
    content: |-
      set-option -g status-style bg=green,fg=colour235
      set-option -g status-left-length 20
      set-option -g status-left "[Session: #S]"
      set-window-option -g window-status-current-style fg=colour253,bg=colour236
      set-window-option -g window-status-current-format " #I: #W "
      set-window-option -g window-status-format " #I: #W "
      set-window-option -g window-status-style fg=colour235
      set -g renumber-windows on
      set-option -g history-limit 100000
      set -g default-terminal "screen-256color"
