---
image:
  distribution: fedora
  release: 35
  architecture: x86_64
  name: "{{ image.distribution }}-{{ image.release }}-{{ image.variant }}-{{ image.serial }}"
  description: "Fedora {{ image.release }} ({{ image.variant }}-{{ image.serial }})"
  variant: default

source:
  downloader: fedora-http
  url: https://kojipkgs.fedoraproject.org

targets:
  lxd:
    vm:
      filesystem: ext4
      size: 21474836480 # 20 GiB

packages:
  manager: dnf
  update: true
  cleanup: true
  sets:
  - packages:
    - bash-completion
    - cloud-init
    - diffutils
    - dnf-plugins-core
    - file
    - findutils
    - gzip
    - iproute
    - iproute-tc
    - iputils
    - jq
    - kbd
    - less
    - lsof
    - man-db
    - man-pages
    - netcat
    - openssh-clients
    - openssh-server
    - passwd
    - procps-ng
    - rsync
    - systemd-networkd
    - systemd-udev
    - socat
    - strace
    - tar
    - tcpdump
    - tmux
    - tree
    - util-linux
    - unzip
    - vim-minimal
    - wget
    - which
    - xz
    action: install

  - packages:
    - cloud-utils-growpart
    - dracut
    - grub2-efi-x64
    - kernel
    - kmod
    - shim
    - lvm2
    action: install
    types:
    - vm

actions:
  # Remove 'nodocs' flags to ensure packages are installed with their manpages
  - trigger: post-unpack
    action: |-
      #!/bin/sh
      set -eux
      sed -i 's|tsflags=nodocs||g' /etc/dnf/dnf.conf

  # Generate machine-id in order for the kernel stuff to be configured properly
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemd-machine-id-setup
    types:
    - vm

  # Manage systemd-resolved stub
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      # systemd-resolved
      umount -l /etc/resolv.conf || true
      rm /etc/resolv.conf
      ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
      # others
      cp -R /etc/skel/.bash* /root/
  
  # Configure timezone
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      ln -sfn /usr/share/zoneinfo/Europe/Paris /etc/localtime
      echo "Europe/Paris" > /etc/timezone
  
  # Default systemd units to enable
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemctl enable systemd-networkd systemd-resolved sshd cloud-init
      systemctl disable systemd-homed
      systemctl mask systemd-oomd
  
  # Additionnal units to manage for VMs
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux
      systemctl enable systemd-timesyncd
    types:
      - vm

  # Remove the "Container Image" string in os-release file
  - trigger: post-files
    action: |-
      #!/bin/sh
      set -eux
      sed -i 's/[ ]*(Container Image)//;/^VARIANT/d' /etc/os-release
  
  - trigger: post-files
    action: |-
      #!/bin/sh
      set -eux
      # Generate grub config
      target=/boot/efi/EFI/fedora/grub.cfg
      grub2-mkconfig -o "${target}"
      sed -i "s#root=[^ ]*#root=/dev/sda2#g" "${target}"
      # Addtionnal fixes
      sed -ri 's#^options .+#options $kernelopts#g' /boot/loader/entries/*
      sed -ri 's|\(Container Image\)||g' /boot/loader/entries/*
      
      # Temporary fix to GRUB entries to ensure VM boots (https://discuss.linuxcontainers.org/t/fedora-vm-fails-to-boot)
      sed -ri 's|/var/cache/distrobuilder.*/rootfs||g' /boot/loader/entries/*
      
      # Generate initramfs
      kver=$(ls /boot/initramfs-*.img | sed -r 's#.*initramfs-(.+)\.img#\1#')
      dracut --kver "${kver}" -f
      
      # Wipe grub environment
      rm -f /boot/efi/EFI/fedora/grubenv
      exit 0
    types:
    - vm

files:
  - name: fstab
    generator: fstab
    types:
    - vm

  - path: /etc/fstab
    generator: dump
    types:
    - container

  - path: /etc/machine-id
    generator: dump
  
  - path: /var/lib/dbus/machine-id
    generator: remove
  
  - path: /etc/hostname
    generator: hostname
  
  - path: /etc/hosts
    generator: hosts

  - name: lxd-agent
    generator: lxd-agent
    types:
    - vm

  - name: meta-data
    generator: cloud-init

  - name: user-data
    generator: cloud-init

  - name: vendor-data
    generator: cloud-init

  - path: /etc/default/grub
    generator: dump
    content: |-
      # Set the recordfail timeout
      GRUB_RECORDFAIL_TIMEOUT=0
      # Do not wait on grub prompt
      GRUB_TIMEOUT=0
      # Set the default commandline
      GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} console=tty1 console=ttyS0"
      # Set the grub console type
      GRUB_TERMINAL=console
      # Disable os-prober
      GRUB_DISABLE_OS_PROBER=true
    types:
    - vm

  - path: /etc/dracut.conf.d/lxd.conf
    generator: dump
    content: |-
      add_drivers+=virtio_scsi
    types:
    - vm

  - path: /etc/sysctl.d/90-tuning.conf
    generator: dump
    content: |-
      vm.dirty_ratio = 30
      vm.dirty_background_ratio = 10
    types:
    - vm
 
  - path: /etc/udev/rules.d/90-tuning.conf
    generator: dump
    content: |-
      ACTION=="add|change", KERNEL=="sd[a-z]", SUBSYSTEM=="block", ATTR{queue/scheduler}="none"
      ACTION=="add|change", KERNEL=="sd[a-z]", SUBSYSTEM=="block", ATTR{queue/read_ahead_kb}="4096"
    types:
    - vm

  - name: eth0.network
    path: /etc/systemd/network/eth0.network
    generator: dump
    content: |-
      [Match]
      Name=eth0
      [Network]
      DHCP=ipv4
    types:
    - container

  - path: /etc/systemd/network/enp5s0.network
    generator: dump
    content: |-
      [Match]
      Name=enp5s0
      [Network]
      DHCP=ipv4
    types:
    - vm

  - path: /etc/systemd/resolved.conf
    generator: dump
    content: |-
      Cache=yes
      DNSStubListener=yes
      ReadEtcHosts=yes
  
  - path: /etc/systemd/journald.conf
    generator: dump
    content: |-
      [Journal]
      Storage=persistent
      Compress=yes
      SystemMaxUse=1G
      SystemMaxFileSize=100M
      MaxRetentionSec=7day
  
  - path: /etc/systemd/timesyncd.conf
    generator: dump
    content: |-
      [Time]
      NTP=0.fr.pool.ntp.org pool 1.fr.pool.ntp.org pool 2.fr.pool.ntp.org
    types:
    - vm

  - path: /etc/dnf/dnf.conf
    generator: dump
    content: |-
      [main]
      gpgcheck=1
      installonly_limit=3
      clean_requirements_on_remove=True
      best=False
      skip_if_unavailable=True
      defaultyes=True
      deltarpm=false
      fastestmirror=false
      max_parallel_downloads=20
  
  - path: /etc/yum.repos.d/fedora-cisco-openh264.repo
    generator: remove

  - path: /etc/ssh/sshd_config
    generator: dump
    content: |-
      Port 22
      HostKey /etc/ssh/ssh_host_ed25519_key
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 30s
      PermitRootLogin no
      AuthenticationMethods publickey
      PubkeyAuthentication yes
      PasswordAuthentication no
      PermitEmptyPasswords no
      AuthorizedKeysFile .ssh/authorized_keys
      UsePAM yes
      X11Forwarding no
      AllowAgentForwarding yes
      PrintMotd yes
      Subsystem sftp internal-sftp
  
  - path: /etc/cloud/cloud.cfg
    generator: dump
    content: |-
      #cloud-config
      users:
        - default
      ssh:
        emit_keys_to_console: false
      cloud_init_modules:
        - write-files
        - users-groups
        - ssh
      cloud_config_modules: {}
      cloud_final_modules: {}
      system_info:
        distro: fedora
        default_user:
          name: core
          lock_passwd: False
          groups: [wheel, adm, systemd-journal]
          sudo: ["ALL=(ALL) NOPASSWD:ALL"]
          shell: /bin/bash
        ssh_svcname: sshd
  
  - path: /etc/tmux.conf
    generator: dump
    content: |-
      set-option -g status-style bg=green,fg=colour235
      set-option -g status-left-length 20
      set-option -g status-left "[Session: #S]"
      set-window-option -g window-status-current-style fg=colour253,bg=colour236
      set-window-option -g window-status-current-format " #I: #W "
      set-window-option -g window-status-format " #I: #W "
      set-window-option -g window-status-style fg=colour235
      set -g renumber-windows on
      set-option -g history-limit 100000
      set -g default-terminal "screen-256color"
